
#### Import NumPy as np

In [10]:
import numpy as np

#### Create an array of 10 zeros 

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 fives

In [61]:
np.ones(10)+4

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [62]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of all the even integers from 10 to 50

In [14]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [21]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [20]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Use NumPy to generate a random number between 0 and 1

In [30]:
np.random.randint(1,2)

1

# Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [32]:
np.random.randn(25)

array([-1.40805119, -0.09687862, -1.05364392,  0.10594048, -0.46287553,
       -0.01256018,  0.14491816,  0.14916268,  0.50714304,  0.27769661,
       -0.69215176, -0.407919  ,  0.57712329, -0.29087794, -1.100264  ,
       -0.87388235, -0.57991552, -0.14143379,  1.42434891,  0.43934062,
       -0.43427299,  0.01691295,  0.42689734,  0.1545088 , -1.35325709])

#### Create the following matrix:

In [33]:
np.random.randn(1,100) ## not understand

array([[-2.10355545e+00, -1.17945685e-01,  3.79911459e-02,
         1.05366308e-01,  1.34120368e+00, -2.69203311e+00,
         5.57237015e-01, -6.27927438e-01,  1.15759602e+00,
         6.01826949e-01, -3.78607880e-01,  5.23427818e-01,
         6.39446429e-01,  6.27882180e-02, -7.76546901e-01,
        -8.06218283e-01, -4.65273820e-01,  3.77458723e-01,
        -9.46661031e-02,  1.54703659e+00, -6.26208501e-01,
        -2.34352882e+00, -1.24299189e+00, -8.91760582e-01,
         3.92514829e-01,  8.86183827e-01,  1.63637842e+00,
        -7.27581238e-01,  5.33751454e-02, -1.37839227e+00,
         1.39460087e-01, -5.54189733e-01,  2.84552123e-01,
        -2.26024560e+00, -1.39078464e+00, -1.94311874e-04,
         7.36857537e-01, -5.12473498e-01, -4.36383190e-01,
        -7.70553230e-01,  1.83634187e+00,  7.69968975e-01,
         1.11278556e+00, -1.71807593e+00, -8.55527460e-01,
         2.72562309e-01,  4.20496790e-01, -5.69238971e-01,
        -1.12071441e+00, -4.33862091e-01, -7.52327176e-0

## Numpy Indexing and Selection


In [34]:
arr=np.arange(1,26).reshape(5,5)

In [42]:
arr



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [45]:
arr[3,4]

20

In [46]:
arr[2:,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [53]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [51]:
arr[4]

array([21, 22, 23, 24, 25])

In [52]:
arr[4,0:5]

array([21, 22, 23, 24, 25])

In [54]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [56]:
arr[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [58]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [59]:
arr.sum()

325

#### Get the standard deviation of the values in mat

In [67]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [70]:
arr.sum(axis=0)

array([55, 60, 65, 70, 75])

In [69]:
arr.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [66]:
arr[:,4:]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [71]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [72]:
np.linspace(55,75,5)

array([55., 60., 65., 70., 75.])